[licenses]
allow = [
    "Apache-2.0",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
    "Zlib",
]

[bans]
multiple-versions = "warn"

[advisories]
ignore = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = [
    "https://github.com/mozilla/rust-code-analysis",
]
