use crate::language::{Language, node_name};
use crate::language_common::{boolean_syntax, statement};
use crate::language_common::{named_reference, qualified_name as qualified};
use crate::semantic::Syntax;
use smackdebt_analysis::{DependencySyntax, NameDeclaration, NameImport, SourceNames, SymbolKind};
use smackdebt_analysis::{Language as ReportLanguage, UnitKind};
use tree_sitter::{Language as Grammar, Node};

pub(crate) struct CSharp;
impl Language for CSharp {
    const REPORT_LANGUAGE: ReportLanguage = ReportLanguage::CSharp;
    fn grammar() -> Grammar {
        tree_sitter_c_sharp::LANGUAGE.into()
    }
    fn unit_query() -> &'static str {
        "[(compilation_unit) (method_declaration) (constructor_declaration) (destructor_declaration) (operator_declaration) (conversion_operator_declaration) (local_function_statement) (accessor_declaration) (property_declaration) (indexer_declaration) (lambda_expression) (anonymous_method_expression)] @unit"
    }
    fn unit_kind(node: Node<'_>) -> Option<UnitKind> {
        match node.kind() {
            "compilation_unit" if has_top_level_work(node) => Some(UnitKind::SyntheticTopLevel),
            "lambda_expression" | "anonymous_method_expression" => Some(UnitKind::Lambda),
            "local_function_statement" => Some(UnitKind::Function),
            "property_declaration" | "indexer_declaration"
                if node
                    .child_by_field_name("value")
                    .is_some_and(|body| body.kind() == "arrow_expression_clause") =>
            {
                Some(UnitKind::Method)
            }
            "method_declaration"
            | "constructor_declaration"
            | "destructor_declaration"
            | "operator_declaration"
            | "conversion_operator_declaration"
            | "accessor_declaration"
                if node.child_by_field_name("body").is_some() =>
            {
                Some(UnitKind::Method)
            }
            _ => None,
        }
    }
    fn is_container(node: Node<'_>) -> bool {
        matches!(
            node.kind(),
            "class_declaration"
                | "struct_declaration"
                | "interface_declaration"
                | "record_declaration"
        )
    }
    fn generated_marker(_: &std::path::Path, source: &[u8]) -> bool {
        std::str::from_utf8(source).is_ok_and(|text| {
            text.lines().take(8).any(|line| {
                let line = line.trim().to_ascii_lowercase();
                (line.starts_with("//") || line.starts_with("/*") || line.starts_with('*'))
                    && (line.contains("<auto-generated") || line.contains("@generated"))
            })
        })
    }
    fn name(node: Node<'_>, source: &[u8]) -> String {
        match node.kind() {
            "compilation_unit" => "<top-level>".to_owned(),
            "lambda_expression" | "anonymous_method_expression" => binding(node, source)
                .unwrap_or_else(|| format!("<lambda {}>", node.start_position().row + 1)),
            "accessor_declaration" => {
                let owner = node
                    .parent()
                    .and_then(|list| list.parent())
                    .map(|owner| node_name(owner, source))
                    .unwrap_or_default();
                format!(
                    "{owner}.{}",
                    node.child_by_field_name("name")
                        .and_then(|name| name.utf8_text(source).ok())
                        .unwrap_or("accessor")
                )
            }
            "operator_declaration" => format!(
                "operator {}",
                node.child_by_field_name("operator")
                    .and_then(|name| name.utf8_text(source).ok())
                    .unwrap_or_default()
            ),
            "conversion_operator_declaration" => format!(
                "operator {}",
                node.child_by_field_name("type")
                    .and_then(|name| name.utf8_text(source).ok())
                    .unwrap_or_default()
            ),
            "indexer_declaration" => "this[]".to_owned(),
            _ => node_name(node, source),
        }
    }
    fn has_declared_identity(node: Node<'_>, _: &[u8]) -> bool {
        !matches!(
            node.kind(),
            "lambda_expression" | "anonymous_method_expression"
        )
    }
    fn match_anchor(node: Node<'_>, source: &[u8]) -> Option<String> {
        binding(node, source).map(|name| format!("binding:{name}"))
    }
    fn parameter_count(node: Node<'_>, _: &[u8]) -> u32 {
        let Some(parameters) = node.child_by_field_name("parameters") else {
            return 0;
        };
        if parameters.kind() == "implicit_parameter" {
            return 1;
        }
        let mut cursor = parameters.walk();
        let regular = parameters
            .named_children(&mut cursor)
            .filter(|child| child.kind() == "parameter")
            .count();
        let variadic = parameters
            .children_by_field_name("name", &mut cursor)
            .count();
        (regular + variadic) as u32
    }
    fn collect_names(node: Node<'_>, source: &[u8], names: &mut SourceNames) {
        collect_names(node, source, names);
    }
    fn dependency(node: Node<'_>, source: &[u8]) -> Option<DependencySyntax> {
        named_dependency(node, source)
    }
    fn container(node: Node<'_>, source: &[u8]) -> Option<String> {
        let name = namespace(node, source, true);
        (!name.is_empty()).then_some(name)
    }
    fn syntax(node: Node<'_>, source: &[u8]) -> Syntax {
        match node.kind() {
            "if_statement" => {
                let alternative = node.parent().is_some_and(|parent| {
                    parent.kind() == "if_statement"
                        && parent.child_by_field_name("alternative") == Some(node)
                });
                let syntax = if alternative {
                    Syntax::alternative(true)
                } else {
                    Syntax::structural(true)
                };
                if node
                    .child_by_field_name("alternative")
                    .is_some_and(|node| node.kind() != "if_statement")
                {
                    syntax.with_alternative()
                } else {
                    syntax
                }
            }
            "for_statement"
            | "foreach_statement"
            | "while_statement"
            | "do_statement"
            | "switch_statement"
            | "switch_expression"
            | "catch_clause"
            | "conditional_expression" => Syntax::structural(true),
            "switch_section" | "switch_expression_arm" => Syntax::alternative(true),
            "binary_expression" | "binary_pattern" => {
                boolean_syntax(node, source).unwrap_or_default()
            }
            kind => statement(
                kind,
                &[
                    "expression_statement",
                    "local_declaration_statement",
                    "return_statement",
                    "throw_statement",
                    "break_statement",
                    "continue_statement",
                    "goto_statement",
                    "yield_statement",
                    "arrow_expression_clause",
                ],
            ),
        }
    }
}
fn has_top_level_work(node: Node<'_>) -> bool {
    let mut cursor = node.walk();
    node.named_children(&mut cursor)
        .any(|child| child.kind() == "global_statement")
}
fn binding(node: Node<'_>, source: &[u8]) -> Option<String> {
    if !matches!(
        node.kind(),
        "lambda_expression" | "anonymous_method_expression"
    ) {
        return None;
    }
    let parent = node.parent()?;
    let declaration = if parent.kind() == "equals_value_clause" {
        parent.parent()?
    } else {
        parent
    };
    let name = declaration
        .child_by_field_name("name")
        .or_else(|| declaration.child_by_field_name("left"))?;
    Some(name.utf8_text(source).ok()?.trim().to_owned())
}

fn namespace(node: Node<'_>, source: &[u8], include_types: bool) -> String {
    let mut segments = Vec::new();
    let mut current = node.parent();
    while let Some(parent) = current {
        if (parent.kind() == "namespace_declaration"
            || include_types && CSharp::is_container(parent))
            && let Some(name) = parent
                .child_by_field_name("name")
                .and_then(|name| name.utf8_text(source).ok())
        {
            segments.push(name.to_owned());
        }
        if parent.kind() == "compilation_unit" {
            let mut cursor = parent.walk();
            if let Some(declaration) = parent
                .named_children(&mut cursor)
                .find(|node| node.kind() == "file_scoped_namespace_declaration")
                && let Some(name) = declaration
                    .child_by_field_name("name")
                    .and_then(|name| name.utf8_text(source).ok())
            {
                segments.push(name.to_owned());
            }
        }
        current = parent.parent();
    }
    segments.reverse();
    segments.join(".")
}

fn import_scope(node: Node<'_>) -> std::ops::Range<usize> {
    std::iter::successors(node.parent(), |node| node.parent())
        .find(|node| matches!(node.kind(), "namespace_declaration" | "compilation_unit"))
        .map_or(0..usize::MAX, |node| node.byte_range())
}
fn import_target(node: Node<'_>, source: &[u8]) -> Option<(String, Option<String>, bool, bool)> {
    if node.kind() != "using_directive" {
        return None;
    }
    let alias_node = node.child_by_field_name("name");
    let alias = alias_node
        .and_then(|node| node.utf8_text(source).ok())
        .map(str::to_owned);
    let mut cursor = node.walk();
    let target = node
        .named_children(&mut cursor)
        .find(|child| {
            Some(*child) != alias_node
                && matches!(
                    child.kind(),
                    "identifier" | "qualified_name" | "alias_qualified_name" | "generic_name"
                )
        })?
        .utf8_text(source)
        .ok()?;
    let global = node
        .children(&mut cursor)
        .any(|child| child.kind() == "global");
    let static_import = node
        .children(&mut cursor)
        .any(|child| child.kind() == "static");
    Some((
        target.trim_start_matches("global::").to_owned(),
        alias,
        global,
        static_import,
    ))
}
fn collect_names(node: Node<'_>, source: &[u8], names: &mut SourceNames) {
    if (CSharp::is_container(node)
        || matches!(node.kind(), "enum_declaration" | "delegate_declaration"))
        && let Some(name) = node
            .child_by_field_name("name")
            .and_then(|name| name.utf8_text(source).ok())
    {
        let mut cursor = node.walk();
        let partial = node.named_children(&mut cursor).any(|child| {
            child.kind() == "modifier" && child.utf8_text(source).ok() == Some("partial")
        });
        names.declare(NameDeclaration::new(
            qualified(&namespace(node, source, true), name),
            SymbolKind::Type,
            partial,
        ));
    }
    if let Some((target, alias, global, _)) = import_target(node, source) {
        names.import(NameImport::new(
            target,
            alias,
            import_scope(node),
            global,
            SymbolKind::Type,
        ));
    }
}
fn named_dependency(node: Node<'_>, source: &[u8]) -> Option<DependencySyntax> {
    if let Some((target, _, _, true)) = import_target(node, source) {
        return Some(name_reference(node, &format!(".{target}"), ""));
    }
    if !matches!(
        node.kind(),
        "identifier" | "qualified_name" | "alias_qualified_name" | "generic_name"
    ) {
        return None;
    }
    let parent = node.parent()?;
    let is_type = parent.child_by_field_name("type") == Some(node)
        || parent.child_by_field_name("returns") == Some(node)
        || matches!(parent.kind(), "base_list" | "type_argument_list")
        || parent.kind() == "attribute" && parent.child_by_field_name("name") == Some(node);
    if !is_type || parent.kind() == "using_directive" {
        return None;
    }
    let raw = node.utf8_text(source).ok()?;
    let name = type_name(raw);
    if is_generic_parameter(node, source, &name) {
        return None;
    }

    Some(name_reference(node, &name, &namespace(node, source, true)))
}
fn name_reference(node: Node<'_>, name: &str, namespace: &str) -> DependencySyntax {
    let name = name
        .strip_prefix("global::")
        .map_or_else(|| name.replace("::", "."), |name| format!(".{name}"));
    named_reference(node, name, namespace.to_owned(), SymbolKind::Type)
}

fn is_generic_parameter(node: Node<'_>, source: &[u8], name: &str) -> bool {
    // Generic parameters belong to the containing declaration, not another file.
    let mut ancestor = node.parent();
    while let Some(parent) = ancestor {
        if let Some(parameters) = parent.child_by_field_name("type_parameters") {
            let mut cursor = parameters.walk();
            if parameters.named_children(&mut cursor).any(|parameter| {
                parameter
                    .child_by_field_name("name")
                    .and_then(|name| name.utf8_text(source).ok())
                    == Some(name)
            }) {
                return true;
            }
        }
        ancestor = parent.parent();
    }
    false
}

fn type_name(raw: &str) -> std::borrow::Cow<'_, str> {
    if !raw.contains('<') {
        return raw.into();
    }
    let mut name = String::with_capacity(raw.len());
    let mut depth = 0usize;
    for character in raw.chars() {
        match character {
            '<' => depth += 1,
            '>' => depth = depth.saturating_sub(1),
            _ if depth == 0 => name.push(character),
            _ => {}
        }
    }
    name.into()
}
