use smackdebt_analysis::{Language, ParseStatus};
use smackdebt_languages::Analyzer;
use std::path::Path;

fn analyze(path: &str, source: &str) -> smackdebt_analysis::FileAnalysis {
    Analyzer::default()
        .analyze(Path::new(path), source.as_bytes().to_vec())
        .unwrap()
}

#[test]
fn csharp_measures_nested_work_independently() {
    let result = analyze("sample.cs", include_str!("fixtures/csharp.cs"));
    assert_eq!(result.language(), Language::CSharp);
    assert_eq!(result.parse_status(), &ParseStatus::Parsed);
    let actual: Vec<_> = result
        .units()
        .iter()
        .map(|unit| {
            let measurements = unit.measurements();
            (
                unit.identity().name(),
                measurements.cognitive_complexity(),
                measurements.cyclomatic_complexity(),
                measurements.logical_lines(),
                measurements.max_nesting(),
                measurements.parameter_count(),
                unit.parent().map(|id| id.index()),
            )
        })
        .collect();
    assert_eq!(
        actual,
        [
            ("Outer", 1, 2, 3, 1, 3, None),
            ("inner", 1, 2, 2, 1, 1, Some(0))
        ]
    );
}

#[test]
fn csharp_namespaces_keep_equal_method_names_distinct() {
    let result = analyze(
        "x.cs",
        "namespace One { class Item { void Run() {} } } namespace Two { class Item { void Run() {} } }",
    );
    assert_eq!(
        result
            .units()
            .iter()
            .map(|unit| unit.identity().container())
            .collect::<Vec<_>>(),
        [Some("One.Item"), Some("Two.Item")]
    );
}

#[test]
fn csharp_parameter_counts_ignore_attributes_and_modifiers() {
    let result = analyze(
        "x.cs",
        "class X { int F([A] int x, ref int y, params int[] rest) => 1; System.Func<int,int> f = x => x; }",
    );
    assert_eq!(
        result
            .units()
            .iter()
            .map(|unit| unit.measurements().parameter_count())
            .collect::<Vec<_>>(),
        [3, 1]
    );
}

#[test]
fn csharp_top_level_work_and_expression_bodies_keep_statements() {
    let result = analyze(
        "x.cs",
        "if (ready) { System.Console.WriteLine(1); } int Local(int x) => x > 0 ? 1 : 0;",
    );
    let values: Vec<_> = result
        .units()
        .iter()
        .map(|unit| {
            let m = unit.measurements();
            (
                m.cognitive_complexity(),
                m.cyclomatic_complexity(),
                m.logical_lines(),
                m.max_nesting(),
                m.parameter_count(),
            )
        })
        .collect();
    assert_eq!(values, [(1, 2, 1, 1, 0), (1, 2, 1, 1, 1)]);
}

#[test]
fn csharp_failures_templates_and_generated_markers_remain_visible() {
    assert_ne!(
        analyze("x.cs", "class X { void Broken( { if (").parse_status(),
        &ParseStatus::Parsed
    );
    for path in ["view.razor", "view.cshtml"] {
        assert!(matches!(
            Analyzer::default().analyze(Path::new(path), b"<h1>view</h1>".to_vec()),
            Err(smackdebt_languages::AnalysisError::Unsupported(_))
        ));
    }
    assert!(Analyzer::has_generated_marker(
        Path::new("x.cs"),
        b"// <auto-generated />\nclass X {}"
    ));
    assert!(!Analyzer::has_generated_marker(
        Path::new("x.cs"),
        b"class X { string message = \"<auto-generated />\"; }"
    ));
}
