use smackdebt_analysis::{Language, ParseStatus};
use smackdebt_languages::Analyzer;
use std::path::Path;

fn analyze(path: &str, source: &str) -> smackdebt_analysis::FileAnalysis {
    Analyzer::default()
        .analyze(Path::new(path), source.as_bytes().to_vec())
        .unwrap()
}

#[test]
fn go_measures_nested_work_independently() {
    let result = analyze("sample.go", include_str!("fixtures/go.go"));
    assert_eq!(result.language(), Language::Go);
    assert_eq!(result.parse_status(), &ParseStatus::Parsed);
    let actual: Vec<_> = result
        .units()
        .iter()
        .map(|unit| {
            let measurements = unit.measurements();
            (
                unit.identity().name(),
                measurements.cognitive_complexity(),
                measurements.cyclomatic_complexity(),
                measurements.logical_lines(),
                measurements.max_nesting(),
                measurements.parameter_count(),
                unit.parent().map(|id| id.index()),
            )
        })
        .collect();
    assert_eq!(
        actual,
        [
            ("outer", 1, 2, 3, 1, 3, None),
            ("inner", 1, 2, 2, 1, 1, Some(0)),
        ]
    );
}

#[test]
fn go_receiver_methods_keep_equal_names_distinct() {
    let result = analyze(
        "x.go",
        "package x\ntype One struct{}\ntype Two struct{}\nfunc (x *One) Run() {}\nfunc (x Two) Run() {}\n",
    );
    assert_eq!(
        result
            .units()
            .iter()
            .map(|unit| unit.identity().container())
            .collect::<Vec<_>>(),
        [Some("One"), Some("Two")]
    );
}

#[test]
fn go_parameter_counts_expand_groups_and_ignore_receivers() {
    let result = analyze(
        "x.go",
        "package x\nfunc f(a,b int, c string, rest ...int) {}\nfunc g(int, string) {}\n",
    );
    assert_eq!(
        result
            .units()
            .iter()
            .map(|unit| unit.measurements().parameter_count())
            .collect::<Vec<_>>(),
        [4, 2]
    );
}

#[test]
fn go_switch_select_and_grouped_cases_have_exact_costs() {
    let result = analyze(
        "x.go",
        "package x\nfunc f(ch chan int, value int) {\n switch value { case 1,2: value++; default: value-- }\n select { case <-ch: value++; default: value-- }\n}\n",
    );
    let measurements = result.units()[0].measurements();
    assert_eq!(
        (
            measurements.cognitive_complexity(),
            measurements.cyclomatic_complexity(),
            measurements.logical_lines(),
            measurements.max_nesting(),
            measurements.parameter_count(),
        ),
        (6, 5, 5, 1, 2)
    );
}

#[test]
fn go_parse_failures_and_generated_markers_remain_visible() {
    assert_ne!(
        analyze("x.go", "package x\nfunc broken( { if {").parse_status(),
        &ParseStatus::Parsed
    );
    assert!(Analyzer::has_generated_marker(
        Path::new("x.go"),
        b"// Code generated by test. DO NOT EDIT.\npackage x\n"
    ));
    assert!(!Analyzer::has_generated_marker(
        Path::new("x.go"),
        b"package x\nvar message = \"Code generated by test. DO NOT EDIT.\""
    ));
}

#[test]
fn react_components_continue_to_use_jsx_and_tsx_analysis() {
    for path in ["View.jsx", "View.tsx"] {
        let source = if path.ends_with(".tsx") {
            "export function View<T,>({ready, items}: {ready: boolean, items: T[]}) { const save = () => { if (ready) work(); }; useEffect(() => { if (ready) save(); }, [ready]); return <main onClick={save}>{ready ? items.map(item => <b>{item}</b>) : null}</main>; }"
        } else {
            "export function View({ready, items}) { const save = () => { if (ready) work(); }; useEffect(() => { if (ready) save(); }, [ready]); return <main onClick={save}>{ready ? items.map(item => <b>{item}</b>) : null}</main>; }"
        };
        let result = analyze(path, source);
        assert_eq!(result.parse_status(), &ParseStatus::Parsed);
        assert_eq!(result.units().len(), 4);
    }
}
