name: Release PR

on:
  push:
    branches: [master]

permissions:
  contents: read

concurrency:
  group: release-plz
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ secrets.RELEASE_PLZ_TOKEN }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: '1.97.0'
      - uses: release-plz/action@v0.5
        with:
          command: release
          version: '0.3.162'
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}

  release-pr:
    needs: release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ secrets.RELEASE_PLZ_TOKEN }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: '1.97.0'
      - uses: release-plz/action@v0.5
        with:
          command: release-pr
          version: '0.3.162'
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
